### ISSUE TITLE
Error al compilar 

### ISSUE THREAD

**Issue by A-deLuna** [Daniel-Orozco/ModVM#3]
> main.cpp:14:5: error: ‘int index’ redeclared as different kind of symbol
>  int index;
>      ^~~~~
> In file included from /usr/include/c++/6.1.1/cstring:42:0,
>                  from main.cpp:3:
> /usr/include/string.h:466:20: note: previous declaration ‘const char\* index(const char*, int)’
>  extern const char *index (const char *__s, int __c)

Esto me pasa porque el `#include <cstring>` de mi compu tiene una [funcion index](http://linux.die.net/man/3/index)
y en main tambien se declara un int index. 

Una posible solucion podria ser poner la variable index en mayusculas o solo la primera letra en mayusculas.

**Comment by Daniel-Orozco** [comment]
cambiaremos "index" a "evindex", gracias
